Repository LaCare-KMUTT/AbdoCare-Web, pull requests merged in 2021-04, with the labels that each got.

#61 Fix dashboard table
  lib/Widget/dashboard/ADL_chart.dart
  lib/Widget/dashboard/bodyTemperature_chart.dart
  lib/Widget/dashboard/dashboardGraph.dart
  lib/Widget/dashboard/dashboard_Table.dart
  lib/Widget/dashboard/linechart.dart
  lib/Widget/dashboard/pain_chart.dart
  lib/Widget/dashboard/post_operation_home/postHomeDashboardDetail.dart
  lib/Widget/dashboard/post_operation_hospital/postHosDashboardDetail.dart
  lib/Widget/dashboard/pre_operation/preDashboardDetail.dart
  lib/Widget/dashboard/pulseRate_chart.dart
Labels: Approved

#60 Query to General Form Previsit
  lib/Widget/dashboard/pre_operation/preDashboardDetail.dart
  lib/Widget/evaluationForms/previsitForm/adlForm.dart
  lib/Widget/evaluationForms/previsitForm/generalForm.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/allergy_medication.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/allergy_to_latex.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/antiPlatelet.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/asaClass.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/consent_sign.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/drug_and_substance.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/generalForm.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/previous_illness.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/psychologicalStatus.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/sleep_disorder.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/type_of_anesthesia.dart
  lib/Widget/material.dart
  lib/Widget/patient_list/editPatientForm.dart
  lib/Widget/post_opeation_hospital/postHosTable.dart
  lib/Widget/post_operation_home/postHomeTable.dart
  lib/Widget/pre_operation/preTable.dart
  lib/Widget/shared/rounded_date_picker.dart
  lib/models/evalutate_form/pre_visit/generalForm_model.dart
  lib/models/evalutate_form/pre_visit/radioListTile_model.dart
  lib/models/evalutate_form/pre_visit/radio_list.dart
  lib/models/user_list/post_home_list_model.dart
  lib/models/user_list/post_hos_list_model.dart
  lib/models/user_list/pre_op_list_model.dart
  lib/services/firebase_service.dart
  lib/services/interfaces/firebase_service_interface.dart
  lib/services/mock/firebase_service_mock.dart
  lib/services/service_locator.dart
  lib/view_models/evaluate_form/generalForm_view_model.dart
  lib/view_models/user_list/post_home_list_view_model.dart
  lib/view_models/user_list/post_hos_list_view_model.dart
  lib/view_models/user_list/pre_op_list_view_model.dart
Labels: ready to review

#65 Refactor ADL Form
  lib/Widget/dashboard/pre_operation/preDashboardDetail.dart
  lib/Widget/evaluationForms/previsitForm/adlForm.dart
  lib/Widget/evaluationForms/previsitForm/adlForm/@enum.dart
  lib/Widget/evaluationForms/previsitForm/adlForm/adlForm.dart
  lib/Widget/evaluationForms/previsitForm/adlForm/adlQuestions.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/allergy_medication.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/allergy_to_latex.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/antiPlatelet.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/asaClass.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/consent_sign.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/drug_and_substance.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/generalForm.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/previous_illness.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/psychologicalStatus.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/sleep_disorder.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/type_of_anesthesia.dart
  lib/Widget/evaluationForms/previsitForm/healthStatus.dart
  lib/models/evalutate_form/pre_visit/adlForm_model.dart
  lib/models/evalutate_form/pre_visit/adlForm_radio_list.dart
  lib/models/evalutate_form/pre_visit/generalForm_radio_list.dart
  lib/models/evalutate_form/pre_visit/radioListTile_model.dart
  lib/view_models/evaluate_form/adlForm_view_model.dart
Labels: ready to review

#66 Add data to notification collection
  lib/Widget/evaluationForms/post-hos/post-hos-day0/respiratory_form.dart
  lib/Widget/evaluationForms/post-hos/post-hos-day0/urology_form.dart
  lib/Widget/evaluationForms/post-hos/post-hos-day1/blood_clot_form.dart
  lib/Widget/evaluationForms/post-hos/post-hos-day1/drain_form.dart
  lib/Widget/evaluationForms/post-hos/post-hos-day1/nutrition_form.dart
  lib/Widget/evaluationForms/post-hos/post-hos-day1/respiratory_form.dart
  lib/Widget/evaluationForms/post-hos/post-hos-day2-7/digestive_form.dart
  lib/Widget/evaluationForms/post-hos/post-hos-day2-7/infection_form.dart
  lib/Widget/evaluationForms/post-hos/post-hos-day2-7/pulmanary_form.dart
  lib/Widget/evaluationForms/post-hos/virtal_sign_form.dart
  lib/Widget/evaluationForms/previsitForm/healthStatus.dart
  lib/Widget/evaluationForms/ultilities/form_utility/pain_form_utility.dart
  lib/Widget/patient_list/patientListTable.dart
  lib/constants.dart
  lib/page/editPatient.dart
  lib/services/firebase_service.dart
  lib/services/interfaces/firebase_service_interface.dart
  lib/services/mock/firebase_service_mock.dart
  test/services_test/calculation_service_test.dart
  test/utilities_test/pain_form_utility_test.dart
Labels: ready to review

#67 Fix previsitForm UI
  lib/Widget/dashboard/post_operation_hospital/postHosDashboardDetail.dart
  lib/Widget/dashboard/pre_operation/preDashboardDetail.dart
  lib/Widget/evaluationForms/post-hos/virtal_sign_form.dart
  lib/Widget/evaluationForms/previsitForm/adlForm/adlForm.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/allergy_medication.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/allergy_to_latex.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/antiPlatelet.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/consent_sign.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/drug_and_substance.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/generalForm.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/previous_illness.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/psychologicalStatus.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/sleep_disorder.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/type_of_anesthesia.dart
  lib/Widget/evaluationForms/previsitForm/healthStatus.dart
  lib/Widget/material.dart
Labels: Approved

#68 Refactor Health Status
  lib/Widget/dashboard/pre_operation/preDashboardDetail.dart
  lib/Widget/evaluationForms/previsitForm/adlForm/adlForm.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/generalForm.dart
  lib/Widget/evaluationForms/previsitForm/healthStatus.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/cv.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/endocrine.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/general.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/gi.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/gyn_uro.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/healthStatus.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/healthStatus_checkbox_list.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/heent.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/heme_lymph.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/ms.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/neuro.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/pulmonary.dart
  lib/Widget/evaluationForms/ultilities/form_utility/pain_form_utility.dart
  lib/models/evalutate_form/pre_visit/checkboxListTile_model.dart
  lib/models/evalutate_form/pre_visit/healthStatusForm_model.dart
  lib/page/addPatient.dart
  lib/page/login.dart
  lib/view_models/evaluate_form/adlForm_view_model.dart
  lib/view_models/evaluate_form/healthStatusForm_view_model.dart
Labels: ready to review

#72 validate health status form
  assets/abdocare_logo.png
  lib/Widget/appointment/appointmentListTable.dart
  lib/Widget/appointment/editAppointment.dart
  lib/Widget/evaluationForms/previsitForm/adlForm/adlForm.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/antiPlatelet.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/generalForm.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/sleep_disorder.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/cv.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/endocrine.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/general.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/gi.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/gyn_uro.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/healthStatus.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/heent.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/heme_lymph.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/ms.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/neuro.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/pulmonary.dart
  lib/Widget/evaluationForms/ultilities/form_utility/health_status_form_utility.dart
  lib/Widget/patient_list/editPatientForm.dart
  lib/Widget/patient_list/patientListTable.dart
  lib/Widget/post_opeation_hospital/postHosTable.dart
  lib/Widget/post_operation_home/postHomeTable.dart
  lib/Widget/pre_operation/preTable.dart
  lib/Widget/shared/progress_bar.dart
  lib/Widget/sidebar.dart
  lib/services/service_locator.dart
  pubspec.yaml
Labels: ready to review

#75 Validate add patient form
  lib/Widget/appointment/addAppointment.dart
  lib/Widget/appointment/editAppointment.dart
  lib/Widget/patient_list/editPatientForm.dart
  lib/Widget/patient_list/patientRegisterForm.dart
  lib/Widget/shared/alert_style.dart
  lib/Widget/sidebar.dart
  lib/page/addPatient.dart
  lib/services/firebase_service.dart
  lib/services/interfaces/firebase_service_interface.dart
  lib/services/mock/firebase_service_mock.dart
  lib/view_models/user_list/post_home_list_view_model.dart
  lib/view_models/user_list/post_hos_list_view_model.dart
  lib/view_models/user_list/pre_op_list_view_model.dart
Labels: ready to review

#78 Create recovery readiness form
  lib/Widget/dashboard/post_operation_hospital/postHosDashboardDetail.dart
  lib/Widget/evaluationForms/post-hos/post-hos-day0/recovery_readiness_form.dart
  lib/Widget/evaluationForms/post-hos/post-hos-day1/drain_form.dart
  lib/view_models/evaluate_form/evaluationFormButton_view_model.dart
Labels: ready to review

#80 Save RecoveryReadiness Data To SubCollection
  lib/Widget/evaluationForms/post-hos/post-hos-day0/recovery_readiness_form.dart
  lib/services/service_locator.dart
  lib/view_models/evaluate_form/recoveryReadiness_view_model.dart
Labels: Approved, ready to review

#73 Query Patient dashboard detail
  .vscode/launch.json
  lib/Widget/dashboard/post_operation_home/postHomeDashboardDetail.dart
  lib/Widget/dashboard/post_operation_home/postHomeDashboardPatientDetail.dart
  lib/Widget/dashboard/post_operation_hospital/postHosDashboardDetail.dart
  lib/Widget/dashboard/post_operation_hospital/postHosDashboardPatientDetail.dart
  lib/Widget/dashboard/pre_operation/preDashboardDetail.dart
  lib/Widget/dashboard/pre_operation/preDashboardPatientDetail.dart
  lib/Widget/dashboard/state_dropdown.dart
  lib/Widget/evaluationForms/previsitForm/adlForm/adlForm.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/antiPlatelet.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/consent_sign.dart
  lib/Widget/evaluationForms/previsitForm/generalForm/generalForm.dart
  lib/Widget/evaluationForms/previsitForm/healthStatusForm/healthStatus.dart
  lib/Widget/shared/alert_style.dart
  lib/models/evalutate_form/pre_visit/generalForm_model.dart
  lib/models/evalutate_form/pre_visit/pre_visit_model.dart
  lib/services/calculation_service.dart
  lib/services/firebase_service.dart
  lib/services/interfaces/calculation_service_interface.dart
  lib/services/interfaces/firebase_service_interface.dart
  lib/services/mock/firebase_service_mock.dart
  lib/services/service_locator.dart
  lib/view_models/evaluate_form/generalForm_view_model.dart
  lib/view_models/evaluate_form/pre_visit_view_model.dart
  test/services_test/calculation_service_test.dart
Labels: ready to review
